{
 "title": "Repository Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo",
    "query": "label_values(MergeSuccessRate, repo)"
   }
  ]
 },
 "panels": [
  {
   "title": "PR Merge Rate (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MergeSuccessRate{repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "PR Median Lifetime (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PRLifetime{repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Average Time to First Review (s)",
   "type": "stat",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TimeToFirstReview{repo=\"$repo\"}"
    }
   ]
  },
  {
   "title": "Predicted Merge Time (s)",
   "type": "stat",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PredictedMergeTime{repo=\"$repo\"}"
    }
   ]
  }
 ]
}